[[constraint]]
  name = "github.com/Azure/draft"
  source = "https://github.com/bacongobbler/draft"
  branch = "pack-repo"

[[constraint]]
  name = "github.com/Sirupsen/logrus"

[[constraint]]
  name = "github.com/spf13/cobra"
